### ISSUE TITLE
Add redis output option

### ISSUE THREAD

**Issue by j91321** [j91321/ansible-role-auditbeat#1]
Add redis output option for auditbeat

Sample variables configuration

```
auditbeat_output:
  type: redis
  redis:
    hosts:
      - "172.16.0.20:6379"
    key: winlogbeat 
    password: supperlongredispasswordbecauseredisisfasttobruteforce
```
