### ISSUE TITLE
Zabbix Agent and Proxy high log volume from system module

### ISSUE THREAD

**Issue by j91321** [j91321/ansible-role-auditbeat#4]
Add processor to system module for ignoring traffic created by Zabbix agent on port 10050. Do the same for Zabbix Proxy.

Sample processor

```
processors:
  - drop_event.when.and:
    - equals.event.action: "network_flow"
    - equals.server.port: 10050
    - equals.process.name: "zabbix_agentd"
```
